spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-write-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      token: last-civilization
  profiles:
    active: dev
server:
  port: 0